apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-lionel-s-legacy-dev
resources:
  - ../../base
labels:
  - includeSelectors: false
    pairs:
      app: lionel-s-legacy
      environment: dev
      tenant: opsera
images:
  - name: all-is-well
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera/lionel-s-legacy
    newTag: dev-26c78239-20260215045337
