apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opsera-lionel-s-legacy-dev
resources:
  - ../../base
labels:
  - includeSelectors: false
    pairs:
      app: lionel-s-legacy
      environment: dev
      tenant: opsera
images:
  - name: all-is-well
    newName: PLACEHOLDER
    newTag: latest
