apiVersion: v1
kind: Service
metadata:
  name: lionel-s-legacy
  labels:
    app: lionel-s-legacy
    tenant: opsera
    managed-by: opsera-c2c
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: lionel-s-legacy
