apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-lionel-s-legacy-dev
  namespace: argocd
  labels:
    app: lionel-s-legacy
    tenant: opsera
    environment: dev
    managed-by: opsera-c2c
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akhilsathwik/lionel-s-legacy.git
    targetRevision: main
    path: .opsera-lionel-s-legacy/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-lionel-s-legacy-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Replace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
